# Generated by Django 4.1 on 2022-09-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_servidor_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='canal_1',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='servidor',
            name='canal_2',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='servidor',
            name='canal_3',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
